name: Daily Commit Workflow

on:
  schedule:
    - cron: '13 4 * * *'  # Runs daily at 04:13 UTC
  workflow_dispatch:      # Allows manual triggering too

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add dummy commit with 24f1001811@ds.study.iitm.ac.in
        run: |
          echo "Daily ping at $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "24f1001811@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily commit at $(date)"
          git push
